[package]
name = "prequen"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
image = "0.25.2"
mint = "0.5.9"
rayon = "1.10.0"
rodio = "0.19.0"
wavegen = "0.4.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "threads"
harness = false